CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS nombre TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW();
UPDATE usuarios SET nombre = '' WHERE nombre IS NULL;
DELETE FROM usuarios WHERE email IS NULL;
ALTER TABLE usuarios ALTER COLUMN nombre SET NOT NULL;
ALTER TABLE usuarios ALTER COLUMN email SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS usuarios_email_key ON usuarios(email);

CREATE TABLE IF NOT EXISTS habitos (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registros (
  id SERIAL PRIMARY KEY,
  habito_id INTEGER NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
  fecha DATE NOT NULL,
  completado BOOLEAN NOT NULL DEFAULT true,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (habito_id, fecha)
);
